# Generated by Django 4.0.4 on 2022-05-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='authOr',
            new_name='author',
        ),
    ]
