# Generated by Django 4.0.4 on 2022-05-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_author_books_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
