# Generated by Django 4.0.4 on 2022-05-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='recommend',
            field=models.BooleanField(default=True),
        ),
    ]
